# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/cadastro_empresa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ct_empresa(object):
    def setupUi(self, ct_empresa):
        ct_empresa.setObjectName("ct_empresa")
        ct_empresa.resize(876, 431)
        ct_empresa.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_empresa = QtWidgets.QFrame(ct_empresa)
        self.fr_empresa.setGeometry(QtCore.QRect(0, 0, 1000, 500))
        self.fr_empresa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_empresa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_empresa.setObjectName("fr_empresa")
        self.lb_FormFornecedor_21 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_21.setGeometry(QtCore.QRect(670, 50, 150, 20))
        self.lb_FormFornecedor_21.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_21.setObjectName("lb_FormFornecedor_21")
        self.tx_TelefoneEmpresa = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_TelefoneEmpresa.setGeometry(QtCore.QRect(20, 205, 196, 25))
        self.tx_TelefoneEmpresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_TelefoneEmpresa.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_TelefoneEmpresa.setPlaceholderText("")
        self.tx_TelefoneEmpresa.setObjectName("tx_TelefoneEmpresa")
        self.lb_FormFornecedor_27 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_27.setGeometry(QtCore.QRect(580, 285, 50, 20))
        self.lb_FormFornecedor_27.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_27.setObjectName("lb_FormFornecedor_27")
        self.tx_RazaoSocial = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_RazaoSocial.setGeometry(QtCore.QRect(20, 135, 321, 25))
        self.tx_RazaoSocial.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_RazaoSocial.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_RazaoSocial.setObjectName("tx_RazaoSocial")
        self.lb_FormFornecedor_28 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_28.setGeometry(QtCore.QRect(20, 285, 50, 20))
        self.lb_FormFornecedor_28.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_28.setObjectName("lb_FormFornecedor_28")
        self.lb_FormFornecedor_20 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_20.setGeometry(QtCore.QRect(660, 285, 120, 20))
        self.lb_FormFornecedor_20.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_20.setObjectName("lb_FormFornecedor_20")
        self.lb_FormFornecedor_17 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_17.setGeometry(QtCore.QRect(350, 110, 150, 20))
        self.lb_FormFornecedor_17.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_17.setObjectName("lb_FormFornecedor_17")
        self.tx_IE = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_IE.setGeometry(QtCore.QRect(350, 75, 196, 25))
        self.tx_IE.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_IE.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_IE.setPlaceholderText("")
        self.tx_IE.setObjectName("tx_IE")
        self.lb_FormFornecedor_26 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_26.setGeometry(QtCore.QRect(20, 340, 120, 20))
        self.lb_FormFornecedor_26.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_26.setObjectName("lb_FormFornecedor_26")
        self.tx_SiteEmpresa = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_SiteEmpresa.setGeometry(QtCore.QRect(236, 205, 196, 25))
        self.tx_SiteEmpresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_SiteEmpresa.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_SiteEmpresa.setPlaceholderText("")
        self.tx_SiteEmpresa.setObjectName("tx_SiteEmpresa")
        self.lb_FormFornecedor_30 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_30.setGeometry(QtCore.QRect(236, 180, 190, 20))
        self.lb_FormFornecedor_30.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_30.setObjectName("lb_FormFornecedor_30")
        self.lb_FormFornecedor_16 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_16.setGeometry(QtCore.QRect(300, 340, 70, 20))
        self.lb_FormFornecedor_16.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_16.setObjectName("lb_FormFornecedor_16")
        self.lb_FormFornecedor_6 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_6.setGeometry(QtCore.QRect(350, 50, 190, 20))
        self.lb_FormFornecedor_6.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_6.setObjectName("lb_FormFornecedor_6")
        self.tx_BairroEmpresa = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_BairroEmpresa.setGeometry(QtCore.QRect(660, 310, 201, 25))
        self.tx_BairroEmpresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_BairroEmpresa.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_BairroEmpresa.setInputMask("")
        self.tx_BairroEmpresa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tx_BairroEmpresa.setPlaceholderText("")
        self.tx_BairroEmpresa.setObjectName("tx_BairroEmpresa")
        self.tx_EstadoEmpresa = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_EstadoEmpresa.setGeometry(QtCore.QRect(300, 365, 70, 25))
        self.tx_EstadoEmpresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_EstadoEmpresa.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_EstadoEmpresa.setInputMask("")
        self.tx_EstadoEmpresa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tx_EstadoEmpresa.setPlaceholderText("")
        self.tx_EstadoEmpresa.setObjectName("tx_EstadoEmpresa")
        self.tx_Cnpj = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_Cnpj.setGeometry(QtCore.QRect(20, 75, 196, 25))
        self.tx_Cnpj.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_Cnpj.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cnpj.setPlaceholderText("")
        self.tx_Cnpj.setObjectName("tx_Cnpj")
        self.tx_NumEmpresa = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_NumEmpresa.setGeometry(QtCore.QRect(579, 310, 71, 25))
        self.tx_NumEmpresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_NumEmpresa.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_NumEmpresa.setInputMask("")
        self.tx_NumEmpresa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tx_NumEmpresa.setPlaceholderText("")
        self.tx_NumEmpresa.setObjectName("tx_NumEmpresa")
        self.lb_FormFornecedor = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor.setGeometry(QtCore.QRect(20, 10, 950, 30))
        self.lb_FormFornecedor.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormFornecedor.setObjectName("lb_FormFornecedor")
        self.lb_FormFornecedor_25 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_25.setGeometry(QtCore.QRect(452, 180, 190, 20))
        self.lb_FormFornecedor_25.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_25.setObjectName("lb_FormFornecedor_25")
        self.lb_FormFornecedor_22 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_22.setGeometry(QtCore.QRect(20, 110, 150, 20))
        self.lb_FormFornecedor_22.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_22.setObjectName("lb_FormFornecedor_22")
        self.tx_CidadeEmpresa = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_CidadeEmpresa.setGeometry(QtCore.QRect(20, 365, 260, 25))
        self.tx_CidadeEmpresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_CidadeEmpresa.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_CidadeEmpresa.setInputMask("")
        self.tx_CidadeEmpresa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tx_CidadeEmpresa.setPlaceholderText("")
        self.tx_CidadeEmpresa.setObjectName("tx_CidadeEmpresa")
        self.frame = QtWidgets.QFrame(self.fr_empresa)
        self.frame.setGeometry(QtCore.QRect(-120, 400, 1000, 40))
        self.frame.setStyleSheet("border-bottom: 2px solid #CCC;\n"
"background: #F7F7F7")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_SalvarDadosEmpresa = QtWidgets.QPushButton(self.frame)
        self.bt_SalvarDadosEmpresa.setGeometry(QtCore.QRect(750, 0, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_SalvarDadosEmpresa.setFont(font)
        self.bt_SalvarDadosEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_SalvarDadosEmpresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_SalvarDadosEmpresa.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_SalvarDadosEmpresa.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_SalvarDadosEmpresa.setIconSize(QtCore.QSize(75, 35))
        self.bt_SalvarDadosEmpresa.setObjectName("bt_SalvarDadosEmpresa")
        self.bt_cancelar_2 = QtWidgets.QPushButton(self.frame)
        self.bt_cancelar_2.setGeometry(QtCore.QRect(880, 0, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cancelar_2.setFont(font)
        self.bt_cancelar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cancelar_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_cancelar_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_cancelar_2.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_cancelar_2.setIconSize(QtCore.QSize(75, 35))
        self.bt_cancelar_2.setObjectName("bt_cancelar_2")
        self.tx_CepEmpresa = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_CepEmpresa.setGeometry(QtCore.QRect(20, 310, 91, 25))
        self.tx_CepEmpresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_CepEmpresa.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_CepEmpresa.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_CepEmpresa.setObjectName("tx_CepEmpresa")
        self.lb_FormFornecedor_29 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_29.setGeometry(QtCore.QRect(160, 285, 250, 20))
        self.lb_FormFornecedor_29.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_29.setObjectName("lb_FormFornecedor_29")
        self.lb_FormFornecedor_9 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_9.setGeometry(QtCore.QRect(20, 180, 196, 20))
        self.lb_FormFornecedor_9.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_9.setObjectName("lb_FormFornecedor_9")
        self.tx_Endereco = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_Endereco.setGeometry(QtCore.QRect(160, 310, 400, 25))
        self.tx_Endereco.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_Endereco.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Endereco.setInputMask("")
        self.tx_Endereco.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tx_Endereco.setPlaceholderText("")
        self.tx_Endereco.setObjectName("tx_Endereco")
        self.tx_EmailEmpresa = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_EmailEmpresa.setGeometry(QtCore.QRect(452, 205, 196, 25))
        self.tx_EmailEmpresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_EmailEmpresa.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_EmailEmpresa.setPlaceholderText("")
        self.tx_EmailEmpresa.setObjectName("tx_EmailEmpresa")
        self.lb_FormFornecedor_18 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_18.setGeometry(QtCore.QRect(20, 50, 190, 20))
        self.lb_FormFornecedor_18.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_18.setObjectName("lb_FormFornecedor_18")
        self.lb_LogoEmpresa = QtWidgets.QLabel(self.fr_empresa)
        self.lb_LogoEmpresa.setGeometry(QtCore.QRect(670, 70, 191, 171))
        self.lb_LogoEmpresa.setStyleSheet("border: 1px solid #A2A2A2;\n"
"")
        self.lb_LogoEmpresa.setText("")
        self.lb_LogoEmpresa.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_LogoEmpresa.setObjectName("lb_LogoEmpresa")
        self.lb_FormFornecedor_31 = QtWidgets.QLabel(self.fr_empresa)
        self.lb_FormFornecedor_31.setGeometry(QtCore.QRect(20, 240, 630, 30))
        self.lb_FormFornecedor_31.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_31.setObjectName("lb_FormFornecedor_31")
        self.tx_NomeFantasia = QtWidgets.QLineEdit(self.fr_empresa)
        self.tx_NomeFantasia.setGeometry(QtCore.QRect(350, 135, 305, 25))
        self.tx_NomeFantasia.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_NomeFantasia.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_NomeFantasia.setObjectName("tx_NomeFantasia")
        self.bt_AddLogo = QtWidgets.QPushButton(self.fr_empresa)
        self.bt_AddLogo.setGeometry(QtCore.QRect(830, 210, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_AddLogo.setFont(font)
        self.bt_AddLogo.setStyleSheet("QPushButton{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_AddLogo.setText("")
        self.bt_AddLogo.setObjectName("bt_AddLogo")
        self.bt_DelLogo = QtWidgets.QPushButton(self.fr_empresa)
        self.bt_DelLogo.setGeometry(QtCore.QRect(830, 210, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_DelLogo.setFont(font)
        self.bt_DelLogo.setStyleSheet("QPushButton{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_DelLogo.setText("")
        self.bt_DelLogo.setObjectName("bt_DelLogo")
        self.bt_busca_cep = QtWidgets.QPushButton(self.fr_empresa)
        self.bt_busca_cep.setGeometry(QtCore.QRect(120, 310, 31, 21))
        self.bt_busca_cep.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imagens/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_busca_cep.setIcon(icon)
        self.bt_busca_cep.setObjectName("bt_busca_cep")
        self.bt_busca_cnpj = QtWidgets.QPushButton(self.fr_empresa)
        self.bt_busca_cnpj.setGeometry(QtCore.QRect(220, 70, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_busca_cnpj.setFont(font)
        self.bt_busca_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_busca_cnpj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_busca_cnpj.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_busca_cnpj.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_busca_cnpj.setIconSize(QtCore.QSize(75, 35))
        self.bt_busca_cnpj.setObjectName("bt_busca_cnpj")
        self.lb_LogoEmpresa.raise_()
        self.bt_DelLogo.raise_()
        self.lb_FormFornecedor_21.raise_()
        self.tx_TelefoneEmpresa.raise_()
        self.lb_FormFornecedor_27.raise_()
        self.tx_RazaoSocial.raise_()
        self.lb_FormFornecedor_28.raise_()
        self.lb_FormFornecedor_20.raise_()
        self.lb_FormFornecedor_17.raise_()
        self.tx_IE.raise_()
        self.lb_FormFornecedor_26.raise_()
        self.tx_SiteEmpresa.raise_()
        self.lb_FormFornecedor_30.raise_()
        self.lb_FormFornecedor_16.raise_()
        self.lb_FormFornecedor_6.raise_()
        self.tx_BairroEmpresa.raise_()
        self.tx_EstadoEmpresa.raise_()
        self.tx_Cnpj.raise_()
        self.tx_NumEmpresa.raise_()
        self.lb_FormFornecedor.raise_()
        self.lb_FormFornecedor_25.raise_()
        self.lb_FormFornecedor_22.raise_()
        self.tx_CidadeEmpresa.raise_()
        self.frame.raise_()
        self.tx_CepEmpresa.raise_()
        self.lb_FormFornecedor_29.raise_()
        self.lb_FormFornecedor_9.raise_()
        self.tx_Endereco.raise_()
        self.tx_EmailEmpresa.raise_()
        self.lb_FormFornecedor_18.raise_()
        self.lb_FormFornecedor_31.raise_()
        self.tx_NomeFantasia.raise_()
        self.bt_AddLogo.raise_()
        self.bt_busca_cep.raise_()
        self.bt_busca_cnpj.raise_()

        self.retranslateUi(ct_empresa)
        QtCore.QMetaObject.connectSlotsByName(ct_empresa)
        ct_empresa.setTabOrder(self.tx_Cnpj, self.tx_IE)
        ct_empresa.setTabOrder(self.tx_IE, self.tx_RazaoSocial)
        ct_empresa.setTabOrder(self.tx_RazaoSocial, self.tx_NomeFantasia)
        ct_empresa.setTabOrder(self.tx_NomeFantasia, self.tx_TelefoneEmpresa)
        ct_empresa.setTabOrder(self.tx_TelefoneEmpresa, self.tx_SiteEmpresa)
        ct_empresa.setTabOrder(self.tx_SiteEmpresa, self.tx_EmailEmpresa)
        ct_empresa.setTabOrder(self.tx_EmailEmpresa, self.tx_CepEmpresa)
        ct_empresa.setTabOrder(self.tx_CepEmpresa, self.bt_busca_cep)
        ct_empresa.setTabOrder(self.bt_busca_cep, self.tx_Endereco)
        ct_empresa.setTabOrder(self.tx_Endereco, self.tx_NumEmpresa)
        ct_empresa.setTabOrder(self.tx_NumEmpresa, self.tx_BairroEmpresa)
        ct_empresa.setTabOrder(self.tx_BairroEmpresa, self.tx_CidadeEmpresa)
        ct_empresa.setTabOrder(self.tx_CidadeEmpresa, self.tx_EstadoEmpresa)
        ct_empresa.setTabOrder(self.tx_EstadoEmpresa, self.bt_AddLogo)
        ct_empresa.setTabOrder(self.bt_AddLogo, self.bt_DelLogo)

    def retranslateUi(self, ct_empresa):
        _translate = QtCore.QCoreApplication.translate
        ct_empresa.setWindowTitle(_translate("ct_empresa", "Cadastro de Empresas"))
        self.lb_FormFornecedor_21.setText(_translate("ct_empresa", "LOGO DA EMPRESA"))
        self.tx_TelefoneEmpresa.setInputMask(_translate("ct_empresa", "(00) 0000-0000"))
        self.tx_TelefoneEmpresa.setText(_translate("ct_empresa", "() -"))
        self.lb_FormFornecedor_27.setText(_translate("ct_empresa", "Nº"))
        self.tx_RazaoSocial.setPlaceholderText(_translate("ct_empresa", "Razão Social"))
        self.lb_FormFornecedor_28.setText(_translate("ct_empresa", "CEP"))
        self.lb_FormFornecedor_20.setText(_translate("ct_empresa", "BAIRRO"))
        self.lb_FormFornecedor_17.setText(_translate("ct_empresa", "NOME FANTASIA"))
        self.lb_FormFornecedor_26.setText(_translate("ct_empresa", "CIDADE"))
        self.lb_FormFornecedor_30.setText(_translate("ct_empresa", "SITE"))
        self.lb_FormFornecedor_16.setText(_translate("ct_empresa", "ESTADO"))
        self.lb_FormFornecedor_6.setText(_translate("ct_empresa", "IE"))
        self.tx_Cnpj.setInputMask(_translate("ct_empresa", "##.###.###/####-##"))
        self.tx_Cnpj.setText(_translate("ct_empresa", "../----"))
        self.lb_FormFornecedor.setText(_translate("ct_empresa", "DADOS DA EMPRESA"))
        self.lb_FormFornecedor_25.setText(_translate("ct_empresa", "Email"))
        self.lb_FormFornecedor_22.setText(_translate("ct_empresa", "RAZÃO SOCIAL"))
        self.bt_SalvarDadosEmpresa.setText(_translate("ct_empresa", "SALVAR"))
        self.bt_cancelar_2.setText(_translate("ct_empresa", "CANCELAR"))
        self.tx_CepEmpresa.setInputMask(_translate("ct_empresa", "99999-999"))
        self.tx_CepEmpresa.setPlaceholderText(_translate("ct_empresa", "123456789"))
        self.lb_FormFornecedor_29.setText(_translate("ct_empresa", "ENDEREÇO"))
        self.lb_FormFornecedor_9.setText(_translate("ct_empresa", "TELEFONE "))
        self.lb_FormFornecedor_18.setText(_translate("ct_empresa", "CNPJ"))
        self.lb_FormFornecedor_31.setText(_translate("ct_empresa", "ENDEREÇO"))
        self.tx_NomeFantasia.setPlaceholderText(_translate("ct_empresa", "NOME FANTASIA"))
        self.bt_AddLogo.setToolTip(_translate("ct_empresa", "<html><head/><body><p>CADASTRAR IMGEM</p></body></html>"))
        self.bt_DelLogo.setToolTip(_translate("ct_empresa", "<html><head/><body><p>Deletar Imagem</p></body></html>"))
        self.bt_busca_cep.setAccessibleName(_translate("ct_empresa", "BUSCA CEP"))
        self.bt_busca_cnpj.setText(_translate("ct_empresa", "BUSCAR CNPJ"))
