# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/cadastro_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ct_FormUsuario(object):
    def setupUi(self, ct_FormUsuario):
        ct_FormUsuario.setObjectName("ct_FormUsuario")
        ct_FormUsuario.resize(678, 460)
        ct_FormUsuario.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormUsuario = QtWidgets.QFrame(ct_FormUsuario)
        self.fr_FormUsuario.setGeometry(QtCore.QRect(0, 0, 681, 500))
        self.fr_FormUsuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_FormUsuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_FormUsuario.setObjectName("fr_FormUsuario")
        self.lb_FormFornecedor_21 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_21.setGeometry(QtCore.QRect(20, 240, 150, 20))
        self.lb_FormFornecedor_21.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_21.setObjectName("lb_FormFornecedor_21")
        self.tx_Celular = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_Celular.setGeometry(QtCore.QRect(20, 205, 196, 25))
        self.tx_Celular.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_Celular.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Celular.setPlaceholderText("")
        self.tx_Celular.setObjectName("tx_Celular")
        self.lb_FormFornecedor_23 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_23.setGeometry(QtCore.QRect(20, 295, 150, 20))
        self.lb_FormFornecedor_23.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_23.setObjectName("lb_FormFornecedor_23")
        self.lb_FormFornecedor_17 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_17.setGeometry(QtCore.QRect(20, 60, 150, 20))
        self.lb_FormFornecedor_17.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_17.setObjectName("lb_FormFornecedor_17")
        self.tx_rg = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_rg.setGeometry(QtCore.QRect(236, 145, 196, 25))
        self.tx_rg.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_rg.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_rg.setPlaceholderText("")
        self.tx_rg.setObjectName("tx_rg")
        self.tx_Telefone = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_Telefone.setGeometry(QtCore.QRect(236, 205, 196, 25))
        self.tx_Telefone.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_Telefone.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Telefone.setPlaceholderText("")
        self.tx_Telefone.setObjectName("tx_Telefone")
        self.lb_FormFornecedor_30 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_30.setGeometry(QtCore.QRect(236, 180, 190, 20))
        self.lb_FormFornecedor_30.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_30.setObjectName("lb_FormFornecedor_30")
        self.lb_FormFornecedor_6 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_6.setGeometry(QtCore.QRect(236, 120, 190, 20))
        self.lb_FormFornecedor_6.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_6.setObjectName("lb_FormFornecedor_6")
        self.tx_cpf = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_cpf.setGeometry(QtCore.QRect(20, 145, 196, 25))
        self.tx_cpf.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_cpf.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_cpf.setPlaceholderText("")
        self.tx_cpf.setObjectName("tx_cpf")
        self.lb_FormFornecedor = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor.setGeometry(QtCore.QRect(20, 10, 971, 30))
        self.lb_FormFornecedor.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormFornecedor.setObjectName("lb_FormFornecedor")
        self.lb_FormFornecedor_25 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_25.setGeometry(QtCore.QRect(452, 180, 190, 20))
        self.lb_FormFornecedor_25.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_25.setObjectName("lb_FormFornecedor_25")
        self.tx_senha = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_senha.setGeometry(QtCore.QRect(20, 320, 300, 25))
        self.tx_senha.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_senha.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tx_senha.setObjectName("tx_senha")
        self.frame = QtWidgets.QFrame(self.fr_FormUsuario)
        self.frame.setGeometry(QtCore.QRect(-330, 420, 1000, 40))
        self.frame.setStyleSheet("border-bottom: 2px solid #CCC;\n"
"background: #F7F7F7")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_salvarUsuario = QtWidgets.QPushButton(self.frame)
        self.bt_salvarUsuario.setGeometry(QtCore.QRect(750, 5, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salvarUsuario.setFont(font)
        self.bt_salvarUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_salvarUsuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_salvarUsuario.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_salvarUsuario.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_salvarUsuario.setIconSize(QtCore.QSize(75, 35))
        self.bt_salvarUsuario.setObjectName("bt_salvarUsuario")
        self.bt_Voltar = QtWidgets.QPushButton(self.frame)
        self.bt_Voltar.setGeometry(QtCore.QRect(880, 5, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_Voltar.setFont(font)
        self.bt_Voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_Voltar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_Voltar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_Voltar.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_Voltar.setIconSize(QtCore.QSize(75, 35))
        self.bt_Voltar.setObjectName("bt_Voltar")
        self.tx_usuario = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_usuario.setGeometry(QtCore.QRect(20, 265, 300, 25))
        self.tx_usuario.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_usuario.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_usuario.setObjectName("tx_usuario")
        self.lb_FormFornecedor_9 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_9.setGeometry(QtCore.QRect(20, 180, 196, 20))
        self.lb_FormFornecedor_9.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_9.setObjectName("lb_FormFornecedor_9")
        self.tx_Email = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_Email.setGeometry(QtCore.QRect(452, 205, 196, 25))
        self.tx_Email.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_Email.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Email.setPlaceholderText("")
        self.tx_Email.setObjectName("tx_Email")
        self.lb_FormFornecedor_18 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_18.setGeometry(QtCore.QRect(20, 120, 190, 20))
        self.lb_FormFornecedor_18.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_18.setObjectName("lb_FormFornecedor_18")
        self.tx_nome = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_nome.setGeometry(QtCore.QRect(20, 85, 630, 25))
        self.tx_nome.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_nome.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_nome.setObjectName("tx_nome")
        self.tx_senha2 = QtWidgets.QLineEdit(self.fr_FormUsuario)
        self.tx_senha2.setGeometry(QtCore.QRect(20, 380, 300, 25))
        self.tx_senha2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_senha2.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_senha2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tx_senha2.setObjectName("tx_senha2")
        self.lb_FormFornecedor_24 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormFornecedor_24.setGeometry(QtCore.QRect(20, 355, 271, 20))
        self.lb_FormFornecedor_24.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_24.setObjectName("lb_FormFornecedor_24")
        self.cb_nivel = QtWidgets.QComboBox(self.fr_FormUsuario)
        self.cb_nivel.setGeometry(QtCore.QRect(350, 340, 291, 25))
        self.cb_nivel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cb_nivel.setStyleSheet("QComboBox{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"+self.resourcepath(\'Images/down.png\')+\");\n"
" }\n"
"")
        self.cb_nivel.setObjectName("cb_nivel")
        self.cb_nivel.addItem("")
        self.cb_nivel.addItem("")
        self.cb_nivel.addItem("")
        self.cb_empresa = QtWidgets.QComboBox(self.fr_FormUsuario)
        self.cb_empresa.setGeometry(QtCore.QRect(350, 270, 271, 25))
        self.cb_empresa.setStyleSheet("QComboBox{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"+self.resourcepath(\'Images/down.png\')+\");\n"
" }\n"
"")
        self.cb_empresa.setObjectName("cb_empresa")
        self.cb_empresa.addItem("")
        self.lb_FormProdutos_3 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormProdutos_3.setGeometry(QtCore.QRect(350, 310, 215, 20))
        self.lb_FormProdutos_3.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_3.setObjectName("lb_FormProdutos_3")
        self.lb_FormProdutos_9 = QtWidgets.QLabel(self.fr_FormUsuario)
        self.lb_FormProdutos_9.setGeometry(QtCore.QRect(350, 240, 215, 20))
        self.lb_FormProdutos_9.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_9.setObjectName("lb_FormProdutos_9")
        self.bt_add_emp = QtWidgets.QPushButton(self.fr_FormUsuario)
        self.bt_add_emp.setGeometry(QtCore.QRect(620, 270, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_add_emp.setFont(font)
        self.bt_add_emp.setStyleSheet("QPushButton{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_add_emp.setText("")
        self.bt_add_emp.setObjectName("bt_add_emp")

        self.retranslateUi(ct_FormUsuario)
        QtCore.QMetaObject.connectSlotsByName(ct_FormUsuario)
        ct_FormUsuario.setTabOrder(self.tx_nome, self.tx_cpf)
        ct_FormUsuario.setTabOrder(self.tx_cpf, self.tx_rg)
        ct_FormUsuario.setTabOrder(self.tx_rg, self.tx_Celular)
        ct_FormUsuario.setTabOrder(self.tx_Celular, self.tx_Telefone)
        ct_FormUsuario.setTabOrder(self.tx_Telefone, self.tx_Email)
        ct_FormUsuario.setTabOrder(self.tx_Email, self.tx_usuario)
        ct_FormUsuario.setTabOrder(self.tx_usuario, self.tx_senha)
        ct_FormUsuario.setTabOrder(self.tx_senha, self.tx_senha2)
        ct_FormUsuario.setTabOrder(self.tx_senha2, self.cb_empresa)
        ct_FormUsuario.setTabOrder(self.cb_empresa, self.bt_add_emp)
        ct_FormUsuario.setTabOrder(self.bt_add_emp, self.cb_nivel)

    def retranslateUi(self, ct_FormUsuario):
        _translate = QtCore.QCoreApplication.translate
        ct_FormUsuario.setWindowTitle(_translate("ct_FormUsuario", "Cadastro de Usuários"))
        self.lb_FormFornecedor_21.setText(_translate("ct_FormUsuario", "USUÁRIO"))
        self.tx_Celular.setInputMask(_translate("ct_FormUsuario", "(00) 00000-0000"))
        self.tx_Celular.setText(_translate("ct_FormUsuario", "() -"))
        self.lb_FormFornecedor_23.setText(_translate("ct_FormUsuario", "SENHA"))
        self.lb_FormFornecedor_17.setText(_translate("ct_FormUsuario", "NOME COMPLETO"))
        self.tx_rg.setInputMask(_translate("ct_FormUsuario", "00.000.000-0"))
        self.tx_Telefone.setInputMask(_translate("ct_FormUsuario", "(00) 0000-0000"))
        self.lb_FormFornecedor_30.setText(_translate("ct_FormUsuario", "TELEFONE"))
        self.lb_FormFornecedor_6.setText(_translate("ct_FormUsuario", "RG"))
        self.tx_cpf.setInputMask(_translate("ct_FormUsuario", "000.000.000-00"))
        self.tx_cpf.setText(_translate("ct_FormUsuario", "..-"))
        self.lb_FormFornecedor.setText(_translate("ct_FormUsuario", "CADASTRO DE USUÁRIO"))
        self.lb_FormFornecedor_25.setText(_translate("ct_FormUsuario", "EMAIL"))
        self.tx_senha.setPlaceholderText(_translate("ct_FormUsuario", "Senha"))
        self.bt_salvarUsuario.setText(_translate("ct_FormUsuario", "SALVAR"))
        self.bt_Voltar.setText(_translate("ct_FormUsuario", "VOLTAR"))
        self.tx_usuario.setPlaceholderText(_translate("ct_FormUsuario", "Usuário"))
        self.lb_FormFornecedor_9.setText(_translate("ct_FormUsuario", "CELULAR"))
        self.lb_FormFornecedor_18.setText(_translate("ct_FormUsuario", "CPF"))
        self.tx_nome.setPlaceholderText(_translate("ct_FormUsuario", "nome completo"))
        self.tx_senha2.setPlaceholderText(_translate("ct_FormUsuario", "Digite sua senha novamente"))
        self.lb_FormFornecedor_24.setText(_translate("ct_FormUsuario", "DIGITE A SENHA NOVAMENTE"))
        self.cb_nivel.setItemText(0, _translate("ct_FormUsuario", "SELECIONE"))
        self.cb_nivel.setItemText(1, _translate("ct_FormUsuario", "VENDEDOR"))
        self.cb_nivel.setItemText(2, _translate("ct_FormUsuario", "GERENTE"))
        self.cb_empresa.setItemText(0, _translate("ct_FormUsuario", "SELECIONE"))
        self.lb_FormProdutos_3.setText(_translate("ct_FormUsuario", "NÍVEL DE ACESSO"))
        self.lb_FormProdutos_9.setText(_translate("ct_FormUsuario", "EMPRESA"))
