# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/UI/lista_empresa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(981, 643)
        Frame.setStyleSheet("background: #FFF;")
        self.fr_titulo_servicos = QtWidgets.QFrame(Frame)
        self.fr_titulo_servicos.setGeometry(QtCore.QRect(0, 0, 981, 60))
        self.fr_titulo_servicos.setStyleSheet("")
        self.fr_titulo_servicos.setObjectName("fr_titulo_servicos")
        self.lb_tituloClientes_2 = QtWidgets.QLabel(self.fr_titulo_servicos)
        self.lb_tituloClientes_2.setGeometry(QtCore.QRect(10, 15, 200, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lb_tituloClientes_2.setFont(font)
        self.lb_tituloClientes_2.setStyleSheet("color: rgb(0, 0, 0)")
        self.lb_tituloClientes_2.setObjectName("lb_tituloClientes_2")
        self.bt_novo = QtWidgets.QPushButton(self.fr_titulo_servicos)
        self.bt_novo.setGeometry(QtCore.QRect(820, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_novo.setFont(font)
        self.bt_novo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_novo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_novo.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_novo.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_novo.setIconSize(QtCore.QSize(75, 35))
        self.bt_novo.setObjectName("bt_novo")
        self.tb_empresa = QtWidgets.QTableWidget(Frame)
        self.tb_empresa.setGeometry(QtCore.QRect(0, 100, 971, 211))
        self.tb_empresa.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_empresa.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tb_empresa.setStyleSheet("QTableView{\n"
"color: #797979;\n"
"font-weight: bold;\n"
"font-size: 13px;\n"
"background: #FFF;\n"
"padding: 0 0 0 5px;\n"
"}\n"
"QHeaderView:section{\n"
"background: #FFF;\n"
"padding: 5px 0 ;\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #797979;\n"
"border: none;\n"
"border-bottom: 2px solid #CCC;\n"
"text-transform: uppercase\n"
"}\n"
"QTableView::item {\n"
"border-bottom: 2px solid #CCC;\n"
"padding: 2px;\n"
"}\n"
"\n"
"")
        self.tb_empresa.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tb_empresa.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tb_empresa.setAutoScrollMargin(20)
        self.tb_empresa.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_empresa.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tb_empresa.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_empresa.setShowGrid(False)
        self.tb_empresa.setGridStyle(QtCore.Qt.NoPen)
        self.tb_empresa.setWordWrap(False)
        self.tb_empresa.setRowCount(1)
        self.tb_empresa.setObjectName("tb_empresa")
        self.tb_empresa.setColumnCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_empresa.setHorizontalHeaderItem(12, item)
        self.tb_empresa.horizontalHeader().setDefaultSectionSize(120)
        self.tb_empresa.horizontalHeader().setHighlightSections(False)
        self.tb_empresa.horizontalHeader().setStretchLastSection(True)
        self.tb_empresa.verticalHeader().setVisible(False)
        self.tb_empresa.verticalHeader().setDefaultSectionSize(50)
        self.tb_empresa.verticalHeader().setMinimumSectionSize(20)
        self.lb_FormProdutos_6 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_6.setGeometry(QtCore.QRect(170, 360, 181, 20))
        self.lb_FormProdutos_6.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_6.setObjectName("lb_FormProdutos_6")
        self.tx_razao_social = QtWidgets.QLineEdit(Frame)
        self.tx_razao_social.setGeometry(QtCore.QRect(170, 380, 301, 25))
        self.tx_razao_social.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_razao_social.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_razao_social.setPlaceholderText("")
        self.tx_razao_social.setObjectName("tx_razao_social")
        self.fr_botoes = QtWidgets.QFrame(Frame)
        self.fr_botoes.setGeometry(QtCore.QRect(0, 610, 991, 30))
        self.fr_botoes.setStyleSheet("background:#E1DFE0;\n"
"border: none;")
        self.fr_botoes.setObjectName("fr_botoes")
        self.bt_cancelar = QtWidgets.QPushButton(self.fr_botoes)
        self.bt_cancelar.setGeometry(QtCore.QRect(860, 0, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cancelar.setFont(font)
        self.bt_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_cancelar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_cancelar.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_cancelar.setIconSize(QtCore.QSize(75, 35))
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.bt_salvar = QtWidgets.QPushButton(self.fr_botoes)
        self.bt_salvar.setGeometry(QtCore.QRect(600, 0, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salvar.setFont(font)
        self.bt_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_salvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_salvar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_salvar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(186, 176, 48);\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"    background-color: rgb(217, 202, 49);\n"
"}")
        self.bt_salvar.setIconSize(QtCore.QSize(75, 35))
        self.bt_salvar.setObjectName("bt_salvar")
        self.bt_excluir = QtWidgets.QPushButton(self.fr_botoes)
        self.bt_excluir.setGeometry(QtCore.QRect(730, 0, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_excluir.setFont(font)
        self.bt_excluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_excluir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_excluir.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_excluir.setStyleSheet("QPushButton {\n"
"    background-color: rgb(203, 46, 46);\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"    background-color: rgb(253, 99, 99);\n"
"}")
        self.bt_excluir.setIconSize(QtCore.QSize(75, 35))
        self.bt_excluir.setObjectName("bt_excluir")
        self.tx_cnpj = QtWidgets.QLineEdit(Frame)
        self.tx_cnpj.setGeometry(QtCore.QRect(10, 380, 151, 25))
        self.tx_cnpj.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_cnpj.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_cnpj.setPlaceholderText("")
        self.tx_cnpj.setObjectName("tx_cnpj")
        self.lb_FormProdutos_7 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_7.setGeometry(QtCore.QRect(10, 360, 61, 20))
        self.lb_FormProdutos_7.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_7.setObjectName("lb_FormProdutos_7")
        self.lb_FormProdutos_8 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_8.setGeometry(QtCore.QRect(480, 360, 111, 20))
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.tx_nome_fantasia = QtWidgets.QLineEdit(Frame)
        self.tx_nome_fantasia.setGeometry(QtCore.QRect(480, 380, 241, 25))
        self.tx_nome_fantasia.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_nome_fantasia.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_nome_fantasia.setInputMask("")
        self.tx_nome_fantasia.setText("")
        self.tx_nome_fantasia.setPlaceholderText("")
        self.tx_nome_fantasia.setObjectName("tx_nome_fantasia")
        self.tx_inscricao = QtWidgets.QLineEdit(Frame)
        self.tx_inscricao.setGeometry(QtCore.QRect(480, 430, 241, 25))
        self.tx_inscricao.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_inscricao.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_inscricao.setText("")
        self.tx_inscricao.setPlaceholderText("")
        self.tx_inscricao.setObjectName("tx_inscricao")
        self.lb_FormProdutos_9 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_9.setGeometry(QtCore.QRect(480, 410, 161, 20))
        self.lb_FormProdutos_9.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_9.setObjectName("lb_FormProdutos_9")
        self.lb_FormProdutos_10 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_10.setGeometry(QtCore.QRect(260, 410, 111, 20))
        self.lb_FormProdutos_10.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_10.setObjectName("lb_FormProdutos_10")
        self.tx_email = QtWidgets.QLineEdit(Frame)
        self.tx_email.setGeometry(QtCore.QRect(260, 430, 211, 25))
        self.tx_email.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_email.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_email.setInputMask("")
        self.tx_email.setText("")
        self.tx_email.setPlaceholderText("")
        self.tx_email.setObjectName("tx_email")
        self.lb_FormProdutos_11 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_11.setGeometry(QtCore.QRect(10, 460, 111, 20))
        self.lb_FormProdutos_11.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_11.setObjectName("lb_FormProdutos_11")
        self.tx_fone = QtWidgets.QLineEdit(Frame)
        self.tx_fone.setGeometry(QtCore.QRect(10, 480, 121, 25))
        self.tx_fone.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_fone.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_fone.setPlaceholderText("")
        self.tx_fone.setObjectName("tx_fone")
        self.lb_FormProdutos_12 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_12.setGeometry(QtCore.QRect(10, 410, 111, 20))
        self.lb_FormProdutos_12.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_12.setObjectName("lb_FormProdutos_12")
        self.tx_site = QtWidgets.QLineEdit(Frame)
        self.tx_site.setGeometry(QtCore.QRect(10, 430, 241, 25))
        self.tx_site.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_site.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_site.setInputMask("")
        self.tx_site.setText("")
        self.tx_site.setPlaceholderText("")
        self.tx_site.setObjectName("tx_site")
        self.lb_FormProdutos = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(10, 520, 971, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.lb_FormProdutos_2 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_2.setGeometry(QtCore.QRect(10, 320, 971, 30))
        self.lb_FormProdutos_2.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos_2.setObjectName("lb_FormProdutos_2")
        self.bt_refresh = QtWidgets.QPushButton(Frame)
        self.bt_refresh.setGeometry(QtCore.QRect(950, 60, 30, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.bt_refresh.setFont(font)
        self.bt_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_refresh.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_refresh.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("View/UI/../Imagens/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_refresh.setIcon(icon)
        self.bt_refresh.setObjectName("bt_refresh")
        self.tx_busca = QtWidgets.QLineEdit(Frame)
        self.tx_busca.setGeometry(QtCore.QRect(190, 60, 731, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tx_busca.setFont(font)
        self.tx_busca.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tx_busca.setStyleSheet("QLineEdit {\n"
"color: #000\n"
"}\n"
"")
        self.tx_busca.setObjectName("tx_busca")
        self.cb_empresa = QtWidgets.QComboBox(Frame)
        self.cb_empresa.setGeometry(QtCore.QRect(10, 60, 171, 31))
        self.cb_empresa.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cb_empresa.setStyleSheet("QComboBox{\n"
"background: #fff;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"Imagens/down.png\");\n"
" }\n"
"")
        self.cb_empresa.setObjectName("cb_empresa")
        self.cb_empresa.addItem("")
        self.bt_busca = QtWidgets.QPushButton(Frame)
        self.bt_busca.setGeometry(QtCore.QRect(920, 60, 30, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.bt_busca.setFont(font)
        self.bt_busca.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_busca.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_busca.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_busca.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("View/UI/../Imagens/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_busca.setIcon(icon1)
        self.bt_busca.setObjectName("bt_busca")
        self.lb_LogoEmpresa = QtWidgets.QLabel(Frame)
        self.lb_LogoEmpresa.setGeometry(QtCore.QRect(750, 380, 161, 141))
        self.lb_LogoEmpresa.setStyleSheet("border: 1px solid #A2A2A2;\n"
"background: url(\'Images/icon/Photo.svg\') center no-repeat \n"
"")
        self.lb_LogoEmpresa.setText("")
        self.lb_LogoEmpresa.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_LogoEmpresa.setObjectName("lb_LogoEmpresa")
        self.bt_DelLogo = QtWidgets.QPushButton(Frame)
        self.bt_DelLogo.setGeometry(QtCore.QRect(880, 490, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_DelLogo.setFont(font)
        self.bt_DelLogo.setStyleSheet("QPushButton{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_DelLogo.setText("")
        self.bt_DelLogo.setObjectName("bt_DelLogo")
        self.bt_AddLogo = QtWidgets.QPushButton(Frame)
        self.bt_AddLogo.setGeometry(QtCore.QRect(880, 490, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_AddLogo.setFont(font)
        self.bt_AddLogo.setStyleSheet("QPushButton{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_AddLogo.setText("")
        self.bt_AddLogo.setObjectName("bt_AddLogo")
        self.lb_FormFornecedor_21 = QtWidgets.QLabel(Frame)
        self.lb_FormFornecedor_21.setGeometry(QtCore.QRect(750, 360, 150, 20))
        self.lb_FormFornecedor_21.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormFornecedor_21.setObjectName("lb_FormFornecedor_21")
        self.lb_FormProdutos_14 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_14.setGeometry(QtCore.QRect(790, 550, 111, 20))
        self.lb_FormProdutos_14.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_14.setObjectName("lb_FormProdutos_14")
        self.tx_rua = QtWidgets.QLineEdit(Frame)
        self.tx_rua.setGeometry(QtCore.QRect(790, 570, 181, 25))
        self.tx_rua.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_rua.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_rua.setInputMask("")
        self.tx_rua.setText("")
        self.tx_rua.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.tx_rua.setPlaceholderText("")
        self.tx_rua.setObjectName("tx_rua")
        self.lb_FormProdutos_19 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_19.setGeometry(QtCore.QRect(10, 550, 141, 20))
        self.lb_FormProdutos_19.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_19.setObjectName("lb_FormProdutos_19")
        self.tx_bairro = QtWidgets.QLineEdit(Frame)
        self.tx_bairro.setGeometry(QtCore.QRect(160, 570, 241, 25))
        self.tx_bairro.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_bairro.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_bairro.setInputMask("")
        self.tx_bairro.setText("")
        self.tx_bairro.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.tx_bairro.setPlaceholderText("")
        self.tx_bairro.setObjectName("tx_bairro")
        self.tx_cep = QtWidgets.QLineEdit(Frame)
        self.tx_cep.setGeometry(QtCore.QRect(10, 570, 101, 25))
        self.tx_cep.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_cep.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_cep.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.tx_cep.setPlaceholderText("")
        self.tx_cep.setObjectName("tx_cep")
        self.bt_busca_cep = QtWidgets.QPushButton(Frame)
        self.bt_busca_cep.setGeometry(QtCore.QRect(110, 570, 31, 25))
        self.bt_busca_cep.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("View/UI/../../Imagens/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_busca_cep.setIcon(icon2)
        self.bt_busca_cep.setObjectName("bt_busca_cep")
        self.tx_cidade = QtWidgets.QLineEdit(Frame)
        self.tx_cidade.setGeometry(QtCore.QRect(520, 570, 191, 25))
        self.tx_cidade.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_cidade.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_cidade.setInputMask("")
        self.tx_cidade.setText("")
        self.tx_cidade.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.tx_cidade.setPlaceholderText("")
        self.tx_cidade.setObjectName("tx_cidade")
        self.tx_numero = QtWidgets.QLineEdit(Frame)
        self.tx_numero.setGeometry(QtCore.QRect(410, 570, 101, 25))
        self.tx_numero.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_numero.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_numero.setInputMask("")
        self.tx_numero.setText("")
        self.tx_numero.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.tx_numero.setPlaceholderText("")
        self.tx_numero.setObjectName("tx_numero")
        self.lb_FormProdutos_16 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_16.setGeometry(QtCore.QRect(410, 550, 181, 20))
        self.lb_FormProdutos_16.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_16.setObjectName("lb_FormProdutos_16")
        self.lb_FormProdutos_17 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_17.setGeometry(QtCore.QRect(520, 550, 111, 20))
        self.lb_FormProdutos_17.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_17.setObjectName("lb_FormProdutos_17")
        self.lb_FormProdutos_18 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_18.setGeometry(QtCore.QRect(720, 550, 61, 20))
        self.lb_FormProdutos_18.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_18.setObjectName("lb_FormProdutos_18")
        self.lb_FormProdutos_15 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_15.setGeometry(QtCore.QRect(160, 550, 111, 20))
        self.lb_FormProdutos_15.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_15.setObjectName("lb_FormProdutos_15")
        self.tx_estado = QtWidgets.QLineEdit(Frame)
        self.tx_estado.setGeometry(QtCore.QRect(720, 570, 61, 25))
        self.tx_estado.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tx_estado.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"padding-left: 3px;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_estado.setInputMask("")
        self.tx_estado.setText("")
        self.tx_estado.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.tx_estado.setPlaceholderText("")
        self.tx_estado.setObjectName("tx_estado")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.tx_cnpj, self.tx_razao_social)
        Frame.setTabOrder(self.tx_razao_social, self.tx_nome_fantasia)
        Frame.setTabOrder(self.tx_nome_fantasia, self.tx_site)
        Frame.setTabOrder(self.tx_site, self.tx_email)
        Frame.setTabOrder(self.tx_email, self.tx_inscricao)
        Frame.setTabOrder(self.tx_inscricao, self.tx_fone)
        Frame.setTabOrder(self.tx_fone, self.tx_cep)
        Frame.setTabOrder(self.tx_cep, self.bt_busca_cep)
        Frame.setTabOrder(self.bt_busca_cep, self.tx_bairro)
        Frame.setTabOrder(self.tx_bairro, self.tx_numero)
        Frame.setTabOrder(self.tx_numero, self.tx_cidade)
        Frame.setTabOrder(self.tx_cidade, self.tx_estado)
        Frame.setTabOrder(self.tx_estado, self.tx_rua)
        Frame.setTabOrder(self.tx_rua, self.tb_empresa)
        Frame.setTabOrder(self.tb_empresa, self.cb_empresa)
        Frame.setTabOrder(self.cb_empresa, self.bt_DelLogo)
        Frame.setTabOrder(self.bt_DelLogo, self.bt_AddLogo)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Lista de Empresas"))
        self.lb_tituloClientes_2.setText(_translate("Frame", "EMPRESAS"))
        self.bt_novo.setText(_translate("Frame", "NOVA EMPRESA"))
        item = self.tb_empresa.verticalHeaderItem(0)
        item.setText(_translate("Frame", "1"))
        item = self.tb_empresa.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "CNPJ"))
        item = self.tb_empresa.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "RAZAO SOCIAL"))
        item = self.tb_empresa.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "NOME FANTASIA"))
        item = self.tb_empresa.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "INSCRIÇÃO ESTADUAL"))
        item = self.tb_empresa.horizontalHeaderItem(4)
        item.setText(_translate("Frame", "EMAIL"))
        item = self.tb_empresa.horizontalHeaderItem(5)
        item.setText(_translate("Frame", "FONE"))
        item = self.tb_empresa.horizontalHeaderItem(6)
        item.setText(_translate("Frame", "SITE"))
        item = self.tb_empresa.horizontalHeaderItem(7)
        item.setText(_translate("Frame", "RUA"))
        item = self.tb_empresa.horizontalHeaderItem(8)
        item.setText(_translate("Frame", "BAIRRO"))
        item = self.tb_empresa.horizontalHeaderItem(9)
        item.setText(_translate("Frame", "NUMERO"))
        item = self.tb_empresa.horizontalHeaderItem(10)
        item.setText(_translate("Frame", "CIDADE"))
        item = self.tb_empresa.horizontalHeaderItem(11)
        item.setText(_translate("Frame", "ESTADO"))
        item = self.tb_empresa.horizontalHeaderItem(12)
        item.setText(_translate("Frame", "CEP"))
        self.lb_FormProdutos_6.setText(_translate("Frame", "RAZAO SOCIAL"))
        self.bt_cancelar.setText(_translate("Frame", "CANCELAR"))
        self.bt_salvar.setText(_translate("Frame", "EDITAR"))
        self.bt_excluir.setText(_translate("Frame", "EXCLUIR"))
        self.tx_cnpj.setInputMask(_translate("Frame", "##.###.###/####-##"))
        self.tx_cnpj.setText(_translate("Frame", "../----"))
        self.lb_FormProdutos_7.setText(_translate("Frame", "CNPJ"))
        self.lb_FormProdutos_8.setText(_translate("Frame", "NOME FANTASIA"))
        self.tx_inscricao.setInputMask(_translate("Frame", "#########"))
        self.lb_FormProdutos_9.setText(_translate("Frame", "INSCRIÇÃO ESTADUAL"))
        self.lb_FormProdutos_10.setText(_translate("Frame", "EMAIL"))
        self.lb_FormProdutos_11.setText(_translate("Frame", "FONE"))
        self.tx_fone.setInputMask(_translate("Frame", "(##) ####-####"))
        self.tx_fone.setText(_translate("Frame", "() -----"))
        self.lb_FormProdutos_12.setText(_translate("Frame", "SITE"))
        self.lb_FormProdutos.setText(_translate("Frame", "ENDEREÇO"))
        self.lb_FormProdutos_2.setText(_translate("Frame", "ALTERAR INFORMAÇÕES"))
        self.bt_refresh.setToolTip(_translate("Frame", "ATUALIZAR TABELA"))
        self.tx_busca.setPlaceholderText(_translate("Frame", "PROCURAR POR..."))
        self.cb_empresa.setItemText(0, _translate("Frame", "SELECIONE"))
        self.bt_busca.setToolTip(_translate("Frame", "BUSCAR"))
        self.bt_DelLogo.setToolTip(_translate("Frame", "<html><head/><body><p>Deletar Imagem</p></body></html>"))
        self.bt_AddLogo.setToolTip(_translate("Frame", "<html><head/><body><p>CADASTRAR IMGEM</p></body></html>"))
        self.lb_FormFornecedor_21.setText(_translate("Frame", "LOGO DA EMPRESA"))
        self.lb_FormProdutos_14.setText(_translate("Frame", "RUA"))
        self.lb_FormProdutos_19.setText(_translate("Frame", "CEP"))
        self.tx_cep.setInputMask(_translate("Frame", "#####-###"))
        self.tx_cep.setText(_translate("Frame", "------"))
        self.bt_busca_cep.setAccessibleName(_translate("Frame", "BUSCA CEP"))
        self.lb_FormProdutos_16.setText(_translate("Frame", "NUMERO"))
        self.lb_FormProdutos_17.setText(_translate("Frame", "CIDADE"))
        self.lb_FormProdutos_18.setText(_translate("Frame", "ESTADO"))
        self.lb_FormProdutos_15.setText(_translate("Frame", "BAIRRO"))
