# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/pesquisa_fornecedores.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(774, 353)
        Frame.setStyleSheet("background: #FFF;")
        self.fr_titulo_servicos = QtWidgets.QFrame(Frame)
        self.fr_titulo_servicos.setGeometry(QtCore.QRect(0, 0, 981, 60))
        self.fr_titulo_servicos.setStyleSheet("")
        self.fr_titulo_servicos.setObjectName("fr_titulo_servicos")
        self.lb_tituloClientes_2 = QtWidgets.QLabel(self.fr_titulo_servicos)
        self.lb_tituloClientes_2.setGeometry(QtCore.QRect(10, 15, 221, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lb_tituloClientes_2.setFont(font)
        self.lb_tituloClientes_2.setStyleSheet("color: rgb(0, 0, 0)")
        self.lb_tituloClientes_2.setObjectName("lb_tituloClientes_2")
        self.bt_novo = QtWidgets.QPushButton(self.fr_titulo_servicos)
        self.bt_novo.setGeometry(QtCore.QRect(610, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_novo.setFont(font)
        self.bt_novo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_novo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_novo.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_novo.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_novo.setIconSize(QtCore.QSize(75, 35))
        self.bt_novo.setObjectName("bt_novo")
        self.tb_fornecedores = QtWidgets.QTableWidget(Frame)
        self.tb_fornecedores.setGeometry(QtCore.QRect(0, 100, 771, 211))
        self.tb_fornecedores.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_fornecedores.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tb_fornecedores.setStyleSheet("QTableView{\n"
"color: #797979;\n"
"font-weight: bold;\n"
"font-size: 13px;\n"
"background: #FFF;\n"
"padding: 0 0 0 5px;\n"
"}\n"
"QHeaderView:section{\n"
"background: #FFF;\n"
"padding: 5px 0 ;\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #797979;\n"
"border: none;\n"
"border-bottom: 2px solid #CCC;\n"
"text-transform: uppercase\n"
"}\n"
"QTableView::item {\n"
"border-bottom: 2px solid #CCC;\n"
"padding: 2px;\n"
"}\n"
"\n"
"")
        self.tb_fornecedores.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tb_fornecedores.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tb_fornecedores.setAutoScrollMargin(20)
        self.tb_fornecedores.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_fornecedores.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tb_fornecedores.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_fornecedores.setShowGrid(False)
        self.tb_fornecedores.setGridStyle(QtCore.Qt.NoPen)
        self.tb_fornecedores.setWordWrap(False)
        self.tb_fornecedores.setRowCount(1)
        self.tb_fornecedores.setObjectName("tb_fornecedores")
        self.tb_fornecedores.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tb_fornecedores.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_fornecedores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_fornecedores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_fornecedores.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_fornecedores.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_fornecedores.setHorizontalHeaderItem(4, item)
        self.tb_fornecedores.horizontalHeader().setDefaultSectionSize(120)
        self.tb_fornecedores.horizontalHeader().setHighlightSections(False)
        self.tb_fornecedores.horizontalHeader().setStretchLastSection(True)
        self.tb_fornecedores.verticalHeader().setVisible(False)
        self.tb_fornecedores.verticalHeader().setDefaultSectionSize(50)
        self.tb_fornecedores.verticalHeader().setMinimumSectionSize(20)
        self.fr_botoes = QtWidgets.QFrame(Frame)
        self.fr_botoes.setGeometry(QtCore.QRect(-210, 320, 991, 30))
        self.fr_botoes.setStyleSheet("background:#E1DFE0;\n"
"border: none;")
        self.fr_botoes.setObjectName("fr_botoes")
        self.bt_selecionar = QtWidgets.QPushButton(self.fr_botoes)
        self.bt_selecionar.setGeometry(QtCore.QRect(860, 0, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_selecionar.setFont(font)
        self.bt_selecionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_selecionar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_selecionar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_selecionar.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_selecionar.setIconSize(QtCore.QSize(75, 35))
        self.bt_selecionar.setObjectName("bt_selecionar")
        self.bt_refresh = QtWidgets.QPushButton(Frame)
        self.bt_refresh.setGeometry(QtCore.QRect(740, 60, 30, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.bt_refresh.setFont(font)
        self.bt_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_refresh.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_refresh.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imagens/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_refresh.setIcon(icon)
        self.bt_refresh.setObjectName("bt_refresh")
        self.tx_busca = QtWidgets.QLineEdit(Frame)
        self.tx_busca.setGeometry(QtCore.QRect(190, 60, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tx_busca.setFont(font)
        self.tx_busca.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tx_busca.setStyleSheet("QLineEdit {\n"
"color: #000\n"
"}\n"
"")
        self.tx_busca.setObjectName("tx_busca")
        self.cb_fornecedores = QtWidgets.QComboBox(Frame)
        self.cb_fornecedores.setGeometry(QtCore.QRect(10, 60, 171, 31))
        self.cb_fornecedores.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cb_fornecedores.setStyleSheet("QComboBox{\n"
"background: #fff;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"Imagens/down.png\");\n"
" }\n"
"")
        self.cb_fornecedores.setObjectName("cb_fornecedores")
        self.cb_fornecedores.addItem("")
        self.bt_busca = QtWidgets.QPushButton(Frame)
        self.bt_busca.setGeometry(QtCore.QRect(710, 60, 30, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.bt_busca.setFont(font)
        self.bt_busca.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_busca.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_busca.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_busca.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Imagens/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_busca.setIcon(icon1)
        self.bt_busca.setObjectName("bt_busca")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.tb_fornecedores, self.cb_fornecedores)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Lista de Fornecedores"))
        self.lb_tituloClientes_2.setText(_translate("Frame", "FORNECEDORES"))
        self.bt_novo.setText(_translate("Frame", "NOVO FORNECEDOR"))
        item = self.tb_fornecedores.verticalHeaderItem(0)
        item.setText(_translate("Frame", "1"))
        item = self.tb_fornecedores.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "ID"))
        item = self.tb_fornecedores.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "NOME FANTASIA"))
        item = self.tb_fornecedores.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "CNPJ"))
        item = self.tb_fornecedores.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "EMAIL"))
        item = self.tb_fornecedores.horizontalHeaderItem(4)
        item.setText(_translate("Frame", "FONE"))
        self.bt_selecionar.setText(_translate("Frame", "SELECIONAR"))
        self.bt_refresh.setToolTip(_translate("Frame", "ATUALIZAR TABELA"))
        self.tx_busca.setPlaceholderText(_translate("Frame", "PROCURAR POR..."))
        self.cb_fornecedores.setItemText(0, _translate("Frame", "SELECIONE"))
        self.bt_busca.setToolTip(_translate("Frame", "BUSCAR"))
