# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/relatorio_movimento.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(692, 281)
        Frame.setStyleSheet("background: #FFF;")
        self.tb_rel = QtWidgets.QTableWidget(Frame)
        self.tb_rel.setGeometry(QtCore.QRect(0, 130, 691, 111))
        self.tb_rel.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_rel.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tb_rel.setStyleSheet("QTableView{\n"
"color: #797979;\n"
"font-weight: bold;\n"
"font-size: 13px;\n"
"background: #FFF;\n"
"padding: 0 0 0 5px;\n"
"}\n"
"QHeaderView:section{\n"
"background: #FFF;\n"
"padding: 5px 0 ;\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #797979;\n"
"border: none;\n"
"border-bottom: 2px solid #CCC;\n"
"text-transform: uppercase;\n"
"}\n"
"QTableView::item {\n"
"border-bottom: 2px solid #CCC;\n"
"padding: 2px;\n"
"}\n"
"\n"
"")
        self.tb_rel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tb_rel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tb_rel.setAutoScrollMargin(20)
        self.tb_rel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_rel.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tb_rel.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_rel.setShowGrid(False)
        self.tb_rel.setGridStyle(QtCore.Qt.NoPen)
        self.tb_rel.setWordWrap(False)
        self.tb_rel.setRowCount(1)
        self.tb_rel.setObjectName("tb_rel")
        self.tb_rel.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tb_rel.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_rel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_rel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_rel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_rel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_rel.setHorizontalHeaderItem(4, item)
        self.tb_rel.horizontalHeader().setDefaultSectionSize(120)
        self.tb_rel.horizontalHeader().setHighlightSections(False)
        self.tb_rel.horizontalHeader().setStretchLastSection(True)
        self.tb_rel.verticalHeader().setVisible(False)
        self.tb_rel.verticalHeader().setDefaultSectionSize(50)
        self.tb_rel.verticalHeader().setMinimumSectionSize(20)
        self.fr_titulo_servicos = QtWidgets.QFrame(Frame)
        self.fr_titulo_servicos.setGeometry(QtCore.QRect(0, 0, 791, 51))
        self.fr_titulo_servicos.setStyleSheet("")
        self.fr_titulo_servicos.setObjectName("fr_titulo_servicos")
        self.lb_venda = QtWidgets.QLabel(self.fr_titulo_servicos)
        self.lb_venda.setGeometry(QtCore.QRect(10, 10, 491, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lb_venda.setFont(font)
        self.lb_venda.setStyleSheet("color: rgb(0, 0, 0)")
        self.lb_venda.setObjectName("lb_venda")
        self.fr_botoes = QtWidgets.QFrame(Frame)
        self.fr_botoes.setGeometry(QtCore.QRect(-290, 250, 991, 30))
        self.fr_botoes.setStyleSheet("background:#E1DFE0;\n"
"border: none;")
        self.fr_botoes.setObjectName("fr_botoes")
        self.bt_sair = QtWidgets.QPushButton(self.fr_botoes)
        self.bt_sair.setGeometry(QtCore.QRect(860, 0, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_sair.setFont(font)
        self.bt_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_sair.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_sair.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_sair.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_sair.setIconSize(QtCore.QSize(75, 35))
        self.bt_sair.setObjectName("bt_sair")
        self.tx_datainicial = QtWidgets.QDateEdit(Frame)
        self.tx_datainicial.setGeometry(QtCore.QRect(10, 80, 141, 31))
        self.tx_datainicial.setObjectName("tx_datainicial")
        self.lb_FormProdutos_7 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_7.setGeometry(QtCore.QRect(10, 60, 101, 20))
        self.lb_FormProdutos_7.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_7.setObjectName("lb_FormProdutos_7")
        self.tx_datafinal = QtWidgets.QDateEdit(Frame)
        self.tx_datafinal.setGeometry(QtCore.QRect(170, 80, 141, 31))
        self.tx_datafinal.setObjectName("tx_datafinal")
        self.lb_FormProdutos_8 = QtWidgets.QLabel(Frame)
        self.lb_FormProdutos_8.setGeometry(QtCore.QRect(170, 60, 101, 20))
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.bt_buscar = QtWidgets.QPushButton(Frame)
        self.bt_buscar.setGeometry(QtCore.QRect(320, 80, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_buscar.setFont(font)
        self.bt_buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_buscar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_buscar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_buscar.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_buscar.setIconSize(QtCore.QSize(75, 35))
        self.bt_buscar.setObjectName("bt_buscar")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Relatório de Movimento"))
        item = self.tb_rel.verticalHeaderItem(0)
        item.setText(_translate("Frame", "1"))
        item = self.tb_rel.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "VENDAS"))
        item = self.tb_rel.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "DESCONTOS"))
        item = self.tb_rel.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "VENDAS LIQ."))
        item = self.tb_rel.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "COMPRAS"))
        item = self.tb_rel.horizontalHeaderItem(4)
        item.setText(_translate("Frame", "LUCRO/PREJUIZO"))
        self.lb_venda.setText(_translate("Frame", "RELATÓRIO DE MOVIMENTO "))
        self.bt_sair.setText(_translate("Frame", "SAIR"))
        self.lb_FormProdutos_7.setText(_translate("Frame", "DATA INICIAL"))
        self.lb_FormProdutos_8.setText(_translate("Frame", "DATA FINAL"))
        self.bt_buscar.setText(_translate("Frame", "BUSCAR"))
